### ISSUE TITLE
OS detection for the raspios arm64

### ISSUE THREAD

**Issue by FredericGuilbault** [OpenCPN/plugins#372]
I was trying to install some o-charts on openCPN. 

The doc says that since openCPN >=5.2 I should install osSENC plugin in the openCPN plugin list inside the application. But I don't see that plugin. ...In fact, I don't see most plugins listed in this repository. 

My hypothesis is that since Im running the new raspios ( not raspbian ) arm64 the kernel declared hostname is Debian not raspbian as it was before.

```bash 
user@lysmarine:~ $ lsb_release -id -s
Debian
Debian GNU/Linux 10 (buster)

user@lysmarine:~ $ dpkg --print-architecture
arm64
```
So openCPN try to list plugins for debian-arm64, but there is none. 

How can I confirm that ? As Im making assumption on how openCPN do the OS and arch detection. But how does this work ? 

Alternatively, If I try to install the plugin from the OS repository the package 
`opencpn-plugin-oernc 1.1.10-1 armhf` allow me to download the charts but don't display them.
`oesenc-pi/bionic,now 4.0.10-0~bionic1 arm64` make openCPN freeze on start (it requires sigkill 9 to shut down)

____
My openCPN install source is `APT-Sources: http://ppa.launchpad.net/opencpn/opencpn/ubuntu bionic/main arm64 Packages`

**Comment by leamas** [comment]
First: the general idea for arm64 is to use flatpak. It is unlikely that there will be plugins available for Debian/arm64

You can verify your assumption by starting opencpn with the `--loglevel debug` option. After a start/exit session, look into the logfile. Here you will find entries like
`Host: init: abi: linuxmint-x86_64, abi_version: 20.1, major ver: 20`  These lines will provide feedback on the actual abi.

**Comment by FredericGuilbault** [comment]
Ill check the logs, but my system is def arm64. Does this mean that if opencpn:arm64 have been installed correctly I sould have flatpack installed and running  ? 


___
Btw im not gonna interfeer but, if i was a contributor of this project, i would had strongly advocate aganst the use of flatpack. It make things faster for dev sure, But cramble like a cancer that kill the linux idea of reusable bricks.  ...and is more likely to waste ram and drive space.

**Comment by leamas** [comment]
>  Does this mean that if opencpn:arm64 have been installed correctly I sould have flatpack installed and running to provide plugin management ?

Yes

---

>  But cramble like a cancer that kill the linux idea of reusable brick

We have a strategic decision to provide x86_64 + armhf native Debian package + Flatpak for other Linux platforms including arm64. Since we have to build binary plugins for all platforms, it's necessary to limit the number of linuxes we support (full stop). I thus don't share your opinion about Flatpak, I accept that it trades compatibility for RAM and disk spec, a trade I find good.
 
Please fee free to support other platforms, it's definitely possible. However, platform support is not just about distributing an OpenCPN build, it's also about building and distributing plugins. It's kind of an echo-system. That said, the resources of the core team is limited and we have to make choices.

**Comment by jongough** [comment]
Not everyone has resources to burn on their navigation system. I certainly don't. CPU, RAM and disk space can be at a premium on smaller systems such as Pi's or older PC's/Mac's/iPad's/Android tablets/Phones, etc.

**Comment by bdbcat** [comment]
"CPU, RAM and disk space can be at a premium on smaller systems such as Pi's or older PC's/Mac's/iPad's/Android tablets/Phones, etc."
No disagreement, in general terms.
But, we are here talking about only RPi ARM64 systems. Most of them have 4 GB ram, easily sufficient for Flatpak.  And we have had no reports of performance problems on this platform with Flatpak.
So I agree that Flatpak is a viable strategy, especially for 64 bit support on RPi4.  We know that 64 bit OS support for RPi4 has turned out to be a very fragmented environment in the field.

**Comment by rgleason** [comment]
I think this topic has been dealt with elsewhere too. Can this please be closed now?

**Comment by rgleason** [comment]
This can be closed now @FredericGuilbault   or @bdbcat

**Comment by rgleason** [comment]
This can be closed, I believe

**Comment by rgleason** [comment]
Close?

**Comment by rgleason** [comment]
Close?

**Comment by rgleason** [comment]
Please close this now.

**Comment by FredericGuilbault** [comment]
I did not have time to test it yet, but ill close on trust that this have been fixed.
