### ISSUE TITLE
Testplugin Template

### ISSUE THREAD

**Issue by rgleason** [OpenCPN/plugins#459]
Most of the the plugins using the TP template will not be supporting Android in the near future.

**Comment by bdbcat** [comment]
More detail, please?

**Comment by rgleason** [comment]
Dave, I am also not capable of doing this, unfortunately. Maybe at some point, but I don't know enough about it to even begin, and I won't get the bulk of the PI done and be spinning wheels.

**Comment by bdbcat** [comment]
OK, understood that the issue is not with TP/FE2, but is actually that "generic" plugin builds do not usually work reasonably on Android devices.
My strategy on this is to monitor requests for specific plugins on Android, and then prioritize the work accordingly.  And there will be judgement calls.  For example, WeatherRouting will be totally impractical on a small touch screen device, so I do not plan to spend much time on it.  This kind of app needs a precise pointing device and a larger display.  Generally, the "denser" the UI, the lower the utility value on Android, thus begetting lower priority.

**Comment by rgleason** [comment]
For a summary of where these plugins are and the issues being found
https://github.com/jongough/testplugin_pi/issues/177

**Comment by rgleason** [comment]
Circleci has shutdown processing for me. About 40% of the jobs from last night processed completely. The rest were started with one or two builds or maybe 4-5 at the most.  The only rerun is using SHA and I don't know if that works yet.

I would like to finish this work, but may not be able to.

**Comment by jongough** [comment]
Circleci is a limited resource for opensource and many of my builds only run a few truly concurrent jobs. But it is free.

You could try contacting circleci and explain what you are doing, i.e. building opensource plugins for an opensource project where the authors are no longer involved in the deployment, so you are having to do more builds that would normally be expected. They may give you dispensation to allow your jobs to run using more resources. I tried it with Travis and they did eventually come back and say yes, but the yes was too restrictive and I would have had the same problem again within a month or so. But circleci may be more receptive.

**Comment by rgleason** [comment]
Going to close this now.  I've written something about the response found here

https://github.com/OpenCPN/plugins/issues/463
