### ISSUE TITLE
ShipDriver Template

### ISSUE THREAD

**Issue by rgleason** [OpenCPN/plugins#462]
We need an update to build macos, 3 flatpaks and android because they are all failing right now.

Logbook for example  https://github.com/jongough/testplugin_pi/issues/177

**Comment by jongough** [comment]
For testplugin, OD and Windvane all the builds work OK. See [https://app.circleci.com/pipelines/github/jongough/testplugin_pi](https://app.circleci.com/pipelines/github/jongough/testplugin_pi). All three use Frontend2 and are exactly the same, the differences are in the developer customised section of CMakeLists.txt. What is the real issue here?

**Comment by bdbcat** [comment]
Rick...
Sorry, I do not see failures to build here:
https://app.circleci.com/pipelines/github/rgleason/LogbookKonni_pi?branch=master
Am I looking at the wrong thing?
Or is it a run-time problem?

**Comment by rgleason** [comment]
Branch update-sd

https://github.com/rgleason/LogbookKonni_pi/tree/update-sd

**Comment by rgleason** [comment]
These are all fixed. Thank you Alec and Mike.
