### ISSUE TITLE
CircleCI Opensource - Concurrency  Limits

### ISSUE THREAD

**Issue by rgleason** [OpenCPN/plugins#463]
As Opensource users of CircleCI services we need to be aware of Concurrency Limits

> Open source organizations on our Free plan receive 400,000 free credits per month that can be spent on Linux open source projects, using a maximum of 4 concurrent jobs.
> 
> If you build on macOS, we also offer organizations on our Free plan 25,000 free credits per month to use on macOS open source builds. For access to this, contact our team at billing@circleci.com. Free credits for macOS open source builds can be used on a maximum of 2 concurrent jobs per organization.

- [CircleCI FAQ](https://circleci.com/docs/2.0/faq/#are-there-credit-plans-for-open-source-projects)
- [Credit Plans for Open Source Projects](https://circleci.com/docs/2.0/faq/#are-there-credit-plans-for-open-source-projects)
- [Are free credits available for macOS open source projects? ](https://support.circleci.com/hc/en-us/articles/360049928971-Are-free-credits-available-for-macOS-open-source-projects-?auth_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY2NvdW50X2lkIjo4MjgyMDksInVzZXJfaWQiOjM5Mzk2MTg5NjIzNCwidGlja2V0X2lkIjo5NzczMCwiZGVmbGVjdGlvbl9pZCI6MTI2MDg4ODA0MzQ1MCwiYXJ0aWNsZXMiOlszNjAwNDk5Mjg5NzEsMzYwMDA3NDQ0MzE0LDM2MDAwODYyMzQxNF0sInRva2VuIjpudWxsLCJleHAiOjE2MzYzNzkwNDN9.xVXMhZhE4qhw2w4kbWnVDlHw0rE547Z1Oz2ZcaJRrUo)  Yes, request from support.
-  [What happens when I run out of credits?](https://circleci.com/docs/2.0/faq/#what-happens-when-i-run-out-of-credits)  On Free plan, jobs will fail to run once you have run out of credits
- [Rate Limits](https://circleci.com/docs/2.0/api-developers-guide/#rate-limits)   CircleCI can throttle jobs as needed.
- [Pricing - See Starting for Free](https://circleci.com/pricing/)    2,500 free credits/wk,  Run 1 job at a time, Build  Linux, Windows, and Arm
- [What is an active user?](https://circleci.com/docs/2.0/faq/#what-constitutes-an-active-user)  Open-source is not considered an active user.
- [Build "Not Running" due to concurrency limit but no other job is running ](https://support.circleci.com/hc/en-us/articles/360055741771?input_string=opencpn+plugins+builds+stop+on+concurrency+limit)
 
### Why is this happening?

> If a job is not starting and showing a status "Not Running" after you triggered a pipeline, it means that you have reached the concurrency limit of your plan.
> 
> This is most likely to happen to customers on our Free Plan, as they have access to use a single container at any one time (1x concurrency), therefore jobs will queue if that container is already in use.
> 
> However, customers on plans with a higher concurrency limit can also encounter this situation.
> 
> The delayed start of your job, and the fact it remains in a "Not Running" state before eventually starting, is due to the fact that other jobs are still running when the new job is triggered.

### Lessons Learned

1. Don't stack up jobs and push all a once.  Spread them out over time.
2. Don't run jobs you don't need.  Don't exceed your monthly limit
3. Don't run environments you don't need. If you are testing one environment, make the run false for the  others.
4. Prune jobs to build just the environments needed.  Don't exceed your monthly limit
5. If you find you need to push a job again quickly, go into your CircleCI dashboard and cancel the rest of the first job from the Dashboard panel viewing all jobs, far left side.
6. Don't run jobs that always fail (in circleci/config.yml set job to false)
7. For example android often fails: If it fails, set those job to false until you  can address the problem.
8. Be patient, jobs run one at a time, and each environment runs one at a time.
9. Example: If you stack up 15 small plugin jobs to run and build, its going to take 2 days.
10. We are hosted for free as opensource.

**Comment by jongough** [comment]
One way to help would be to use 'circleci local' to do the initial builds. This works for all except the 'armhf' jobs which use a 'machine' executer. To run these you will need a virtual machine the same as the machine image, then you can setup the environment and run the commands needed from the command line. It is a bit messy but it does work.

For circleci local I run this command in the root directory of the plugin I am building for:
```
circleci local execute --job build-focal-gtk3 -e CIRCLECI_LOCAL=true -e CLOUDSMITH_API_KEY="123" --volume /home/jon/opencpn/circleci-output:/home/circleci/circleci-output -e LOCAL_DEPLOY=true
```
You will need to change the directory after `--volume` to be somewhere on your filesystem that you want to store the final tar files. These are then in a format that can be directly imported by Plugin Manger using the import button. Once this has been done you can, if needed for debugging, build the lib file using an IDE and copy it over the top of the installed one. This will allow debugging from within OCPN and you can see where the failure is (I did this for a couple of the plugins you were having difficulty with).

Depending on your internet connection you may need to update the docker images being used to avoid the continual download and install of updates. I do this when I have to do more than a few runs. You would need to use docker commands for this and make 'test' changes to the config.yml file to use your image rather than the default one, but.....

Anyway, doing circleci local should possibly be the first pass tests for any plugin you are changing. I know that it has to be tested against the cloud based circleci at the end and that some tests can ONLY be done in the cloud environment, but that is normally when I am building new capabilities for builds, rather than when you are modifying existing plugins.

**Comment by rgleason** [comment]
I received a response to my questions about Concurrency and OpenSource, from CircleCI Support: 

1. Information on open source projects on CircleCI is available here: https://circleci.com/docs/2.0/oss/
2. You will also need to set the option for your project under Advanced Settings to set the project as Free and Open Source or you will be limited to 1 concurrency.

In regards to your questions.

1. I pushed too many separate jobs at once and they still have not been completed overnight.

> Concurrency is shared across all projects at an organization, so the issue could be that other projects are building and blocking your current build which is why it did not complete overnight.

  2. I should just be patient and let Circleci have enough time to complete everything?

> If you are able to provide us with a link to your CircleCI project we will be happy to look into this for you.

    3. But it looks like the jobs have been forgotten and there is no job running right now. How do I find out which job is running or if Circleci has stopped working completely on my jobs?

> You can use the API to pull the most recent builds ordered by build_num using the following: curl https://circleci.com/api/v1.1/recent-builds?limit=1&shallow=true

> The second option is to use the following URL replacing the vcs, org and project with your settings ~https://app.circleci.com/pipelines/(vcs)/(org)/(project)/jobs`

> More information can be found here: https://support.circleci.com/hc/en-us/articles/360047731771-How-to-view-all-jobs-for-a-project


    4. I may have run out of credits for the month and the jobs may permanently paused until the end of the month. (How would I know this?)

> You can check by going from the dashboard and clicking the plan button which will show your credits.


> If you have any questions please feel free to ask.

**Comment by rgleason** [comment]
Common knowledge now. Closing
